# Generated by Django 2.2.16 on 2022-03-18 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, verbose_name='Сведения о пользователе'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'Пользователь с паролем'), ('moderator', 'Модератор'), ('admin', 'Админ')], default='user', max_length=40, verbose_name='Роль пользователя'),
        ),
    ]
