# Generated by Django 2.2.16 on 2022-03-24 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220318_0526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'Пользователь с паролем'), ('moderator', 'Модератор'), ('admin', 'Админ')], default='user', max_length=20, verbose_name='Роль пользователя'),
        ),
    ]
